### ISSUE TITLE
Using KUMA_API_SERVER_BASE_PATH can cause a panic

### ISSUE THREAD

**Issue by johncowen** [kumahq/kuma#12335]
### What happened?

`KUMA_API_SERVER_BASE_PATH=ui kuma-cp run` using the latest binary from the install script causes a panic:

```
panic: parsing "ui": at offset 0: host/path missing /

goroutine 1 [running]:
net/http.(*ServeMux).register(...)
        net/http/server.go:2797
net/http.(*ServeMux).HandleFunc(0x1400007401a?, {0x1400007401a?, 0x102caef14?}, 0x1036a1a08?)
        net/http/server.go:2771 +0x78
github.com/emicklei/go-restful/v3.(*Container).addHandler(0x140004d8bd0, 0x140008dcc40, 0x140008dcb60)
        github.com/emicklei/go-restful/v3@v3.12.1/container.go:132 +0x1e8
github.com/emicklei/go-restful/v3.(*Container).Add(0x140004d8bd0, 0x140008dcc40)
        github.com/emicklei/go-restful/v3@v3.12.1/container.go:107 +0x1b8
github.com/kumahq/kuma/pkg/api-server.NewApiServer({0x10373a5e0, 0x1400094fef0}, {0x103708a00, 0x14000a89440}, {0x1400063e008, 0x30, 0x49}, 0x14000b12e08, {0x0, 0x0, ...})
        github.com/kumahq/kuma/pkg/api-server/server.go:180 +0xc80
github.com/kumahq/kuma/pkg/api-server.SetupServer({0x10373a5e0, 0x1400094fef0})
        github.com/kumahq/kuma/pkg/api-server/server.go:469 +0x3f0
github.com/kumahq/kuma/app/kuma-cp/cmd.newRunCmdWithOpts.func1(0x14000ae1b08, {0x1025d6460?, 0x4?, 0x1025d6464?})
        github.com/kumahq/kuma/app/kuma-cp/cmd/run.go:136 +0x4a0
github.com/spf13/cobra.(*Command).execute(0x14000ae1b08, {0x10592d640, 0x0, 0x0})
        github.com/spf13/cobra@v1.8.1/command.go:985 +0x834
github.com/spf13/cobra.(*Command).ExecuteC(0x14000ae1808)
        github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/kumahq/kuma/app/kuma-cp/cmd.Execute()
        github.com/kumahq/kuma/app/kuma-cp/cmd/root.go:83 +0x20
main.main()
        github.com/kumahq/kuma/app/kuma-cp/main.go:6 +0x1c
```

**Comment by SuhasHareesh** [comment]
Hi @johncowen, This is my first time working on an open source project. I wanted to know if I can work on this issue and I kindly ask for your guidance in this issue as well. Thanks!

**Comment by lahabana** [comment]
@SuhasHareesh yes please go ahead. We work with forks so just fork the repo and open a PR. 
Here's more info on the process etc: https://github.com/kumahq/kuma/blob/master/CONTRIBUTING.md

**Comment by saurabhsadhale** [comment]
@johncowen  I think the value passed to the environment variable is wrongly configured. The logs suggest that it is expecting a "path" something like "/ui/". 

I have tried configuring a similar setup using a "proper path"  and it has worked for me. Let me know if running a command something like the following it should work: 

$ KUMA_API_SERVER_BASE_PATH=/ui kuma-cp run

**Comment by johncowen** [comment]
Hey @saurabhsadhale ! 👋 

> I have tried configuring a similar setup using a "proper path" and it has worked for me. Let me know if running a command something like the following it should work:

Yes totally get you 🙌 , my main issue was I believe it shouldn't panic if someone doesn't do that, but instead validate the path and give some sort of guidance as to what the user is doing wrong.

Lemme know if that make sense 👍
