### ISSUE TITLE
pod/prometheus-server get status CrashLoopBackOff

### ISSUE THREAD

**Issue by RedBoneZhang** [kumahq/kuma#2449]
### Summary
After kumactl install metrics | kubectl apply -f -，pod/prometheus-server get status CrashLoopBackOff.

### Steps To Reproduce

1. https://kuma.io/docs/1.2.2/quickstart/kubernetes/
2. use hostpath in PVC.

### Additional Details & Logs

- Version
```
[root@iaas-dev0010 ~]# kumactl version
Kuma: 1.2.2

 [root@iaas-dev0010 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Error logs
```
[root@iaas-dev0010 ~]# kubectl -n kuma-metrics describe pod prometheus-server-54b6fb486d-48xc7
Name:         prometheus-server-54b6fb486d-48xc7
Namespace:    kuma-metrics
Priority:     0
Node:         iaas-dev0010/192.168.64.7
Start Time:   Thu, 29 Jul 2021 14:26:36 +0800
Labels:       app=prometheus
              component=server
              pod-template-hash=54b6fb486d
Annotations:  kuma.io/builtindns: enabled
              kuma.io/builtindnsport: 15053
              kuma.io/direct-access-services: *
              kuma.io/mesh: default
              kuma.io/sidecar-injected: true
              kuma.io/sidecar-uid: 5678
              kuma.io/transparent-proxying: enabled
              kuma.io/transparent-proxying-inbound-port: 15006
              kuma.io/transparent-proxying-inbound-v6-port: 15010
              kuma.io/transparent-proxying-outbound-port: 15001
              kuma.io/virtual-probes: enabled
              kuma.io/virtual-probes-port: 9000
Status:       Running
IP:           10.244.0.40
IPs:
  IP:           10.244.0.40
Controlled By:  ReplicaSet/prometheus-server-54b6fb486d
Init Containers:
  kuma-init:
    Container ID:  docker://c4604bd8ddac126725626444d23d322b807c93a19619d1b9ed77a8eda6cdc4be
    Image:         docker.io/kumahq/kuma-init:1.2.2
    Image ID:      docker-pullable://kumahq/kuma-init@sha256:59e693dd66ddc01a9b7c9f7b0f71b78fb75e24346a7639fe92b62ad34f6e437d
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/kumactl
      install
      transparent-proxy
    Args:
      --redirect-outbound-port
      15001
      --redirect-inbound=true
      --redirect-inbound-port
      15006
      --redirect-inbound-port-v6
      15010
      --kuma-dp-uid
      5678
      --exclude-inbound-ports
      
      --exclude-outbound-ports
      
      --verbose
      --skip-resolv-conf
      --redirect-all-dns-traffic
      --redirect-dns-port
      15053
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 29 Jul 2021 14:26:38 +0800
      Finished:     Thu, 29 Jul 2021 14:26:38 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  50M
    Requests:
      cpu:        10m
      memory:     10M
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from prometheus-server-token-7r8b6 (ro)
Containers:
  prometheus-server-configmap-reload:
    Container ID:  docker://c45a9736fefe9d04be21a0cead5b738d591c3fdf189ce6be9faf7b4d66bf0d00
    Image:         jimmidyson/configmap-reload:v0.5.0
    Image ID:      docker-pullable://jimmidyson/configmap-reload@sha256:904d08e9f701d3d8178cb61651dbe8edc5d08dd5895b56bdcac9e5805ea82b52
    Port:          <none>
    Host Port:     <none>
    Args:
      --volume-dir=/etc/config
      --webhook-url=http://127.0.0.1:9090/-/reload
    State:          Running
      Started:      Thu, 29 Jul 2021 14:26:39 +0800
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/config from config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from prometheus-server-token-7r8b6 (ro)
  prometheus-server:
    Container ID:  docker://abdae9a2eb302e327be32add9fca7c96396c23701927612143e0e30976759783
    Image:         prom/prometheus:v2.27.1
    Image ID:      docker-pullable://prom/prometheus@sha256:5accb68b56ba452e449a5e552411acaeabbbe0f087acf19a1157ce3dd10a8bed
    Port:          9090/TCP
    Host Port:     0/TCP
    Args:
      --storage.tsdb.retention.time=15d
      --config.file=/etc/config/prometheus.yml
      --storage.tsdb.path=/data
      --web.console.libraries=/etc/prometheus/console_libraries
      --web.console.templates=/etc/prometheus/consoles
      --web.enable-lifecycle
    State:          Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Thu, 29 Jul 2021 14:26:56 +0800
      Finished:     Thu, 29 Jul 2021 14:26:56 +0800
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Thu, 29 Jul 2021 14:26:40 +0800
      Finished:     Thu, 29 Jul 2021 14:26:41 +0800
    Ready:          False
    Restart Count:  2
    Environment:    <none>
    Mounts:
      /data from storage-volume (rw)
      /etc/config from config-volume (rw)
      /var/run/kuma.io/prometheus-sd from kuma-prometheus-sd-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from prometheus-server-token-7r8b6 (ro)
  kuma-prometheus-sd:
    Container ID:  docker://f6a539537e5c1fda3cda0a1d4e1167504178f6177f15bf38057bf00c2eb27e5a
    Image:         docker.io/kumahq/kuma-prometheus-sd:1.2.2
    Image ID:      docker-pullable://kumahq/kuma-prometheus-sd@sha256:5596d76832dfbc949a10ec6ad3e4824b5cc3421e8a3b05e5281ab9230d5e3d7b
    Port:          <none>
    Host Port:     <none>
    Args:
      run
      --name=kuma-prometheus-sd
      --cp-address=grpc://kuma-control-plane.kuma-system:5676
      --output-file=/var/run/kuma.io/prometheus-sd/kuma.file_sd.json
    State:          Running
      Started:      Thu, 29 Jul 2021 14:26:40 +0800
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/kuma.io/prometheus-sd from kuma-prometheus-sd-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from prometheus-server-token-7r8b6 (ro)
  kuma-sidecar:
    Container ID:  docker://f5905aaf2dfe9ddba71605744df495ebad042bea01e13e09504b4142616a3461
    Image:         docker.io/kumahq/kuma-dp:1.2.2
    Image ID:      docker-pullable://kumahq/kuma-dp@sha256:648851cc2ba783a3ae36d5a08b5f02ed0580800c370fb12e575290f6eb98a90e
    Port:          <none>
    Host Port:     <none>
    Args:
      run
      --log-level=info
    State:          Running
      Started:      Thu, 29 Jul 2021 14:26:40 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  512Mi
    Requests:
      cpu:      50m
      memory:   64Mi
    Liveness:   http-get http://:9901/ready delay=60s timeout=3s period=5s #success=1 #failure=12
    Readiness:  http-get http://:9901/ready delay=1s timeout=3s period=5s #success=1 #failure=12
    Environment:
      POD_NAME:                           prometheus-server-54b6fb486d-48xc7 (v1:metadata.name)
      POD_NAMESPACE:                      kuma-metrics (v1:metadata.namespace)
      INSTANCE_IP:                         (v1:status.podIP)
      KUMA_CONTROL_PLANE_CA_CERT:         -----BEGIN CERTIFICATE-----
                                          MIIDEDCCAfigAwIBAgIRANXLzDMhPmO8WsXFp4UVmn4wDQYJKoZIhvcNAQELBQAw
                                          EjEQMA4GA1UEAxMHa3VtYS1jYTAeFw0yMTA3MjgwNjI4MjJaFw0zMTA3MjYwNjI4
                                          MjJaMBIxEDAOBgNVBAMTB2t1bWEtY2EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
                                          ggEKAoIBAQCnGwHOFkRTQ0/felIWJT2lYffFBNOv0S9wv1+pyD1egcbXPWadtf+e
                                          agER8nIoCkcCBbB+QFSu0xgPOyNjqaQYDPLXEJoVn9blYAk6OX8n0ilf3WssjiQU
                                          zsRGZdmATfRUpK77fCXOiKnMI6ZzSZ9I9Q63w4Dcx6DpWTsDGx3XZLGWpgXAj9y3
                                          Eqd5AlqZvK335wFKfVHi9xZaZPGiNOPODv4lr7M6AQ9T241Ptek7yS0YugaWcvvE
                                          Fh1w43Sl7MkYs1k+vv1KVGWyqAPYxehpc0wfIU8oOlgyd2AUcJ/Q9/aBGmUn3WhW
                                          dLugk6qLt5FFq5GI/y5Yw0M/UbSsVHoZAgMBAAGjYTBfMA4GA1UdDwEB/wQEAwIC
                                          pDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDwYDVR0TAQH/BAUwAwEB
                                          /zAdBgNVHQ4EFgQU4Rvf1KjzbSF0IyKbCd1miSlsa1cwDQYJKoZIhvcNAQELBQAD
                                          ggEBAHI4u+zByQPTc6gbvuJBtzcA9GfX9NEtcOdZ/zLoAmJ4lU5b7waL86wFb2jz
                                          +D9kdoBs5tsFCSCajHMVWBezJjyJiPUKlxE/bVZO1CnTEAL0G5qtLs0dxl9ZC4EX
                                          qNGr+AgDGkpW7GFEZjCxXXK5DhyQpGRO/xuSsaoKAhaL92sy79IvbPFJu8ZS/skc
                                          OijTO8jtfCUc6w629ETQ2MAl0fm6cmPz+miD5NdlElWNt9Xyly1HCSGwDyNmmoE7
                                          hcvpsjAaL+TcYuQuhfQtqntpQivc9RLz0Pj+It/198iOawRtQe9pj5GtCkKa6Ffy
                                          6br8HJvEeItLr6DPYRuAyO9Xwk0=
                                          -----END CERTIFICATE-----
                                          
      KUMA_CONTROL_PLANE_URL:             https://kuma-control-plane.kuma-system:5678
      KUMA_DATAPLANE_ADMIN_PORT:          9901
      KUMA_DATAPLANE_DRAIN_TIME:          30s
      KUMA_DATAPLANE_MESH:                default
      KUMA_DATAPLANE_NAME:                $(POD_NAME).$(POD_NAMESPACE)
      KUMA_DATAPLANE_RUNTIME_TOKEN_PATH:  /var/run/secrets/kubernetes.io/serviceaccount/token
      KUMA_DNS_CORE_DNS_BINARY_PATH:      coredns
      KUMA_DNS_CORE_DNS_EMPTY_PORT:       15054
      KUMA_DNS_CORE_DNS_PORT:             15053
      KUMA_DNS_ENABLED:                   true
      KUMA_DNS_ENVOY_DNS_PORT:            15055
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from prometheus-server-token-7r8b6 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      prometheus-server
    Optional:  false
  storage-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  prometheus-server
    ReadOnly:   false
  kuma-prometheus-sd-volume:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  prometheus-server-token-7r8b6:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  prometheus-server-token-7r8b6
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                Age               From                             Message
  ----     ------                ----              ----                             -------
  Normal   Scheduled             25s               default-scheduler                Successfully assigned kuma-metrics/prometheus-server-54b6fb486d-48xc7 to iaas-dev0010
  Normal   Pulled                25s               kubelet                          Container image "docker.io/kumahq/kuma-init:1.2.2" already present on machine
  Normal   Created               25s               kubelet                          Created container kuma-init
  Normal   Started               24s               kubelet                          Started container kuma-init
  Normal   CreatedKumaDataplane  24s               k8s.kuma.io/dataplane-generator  Created Kuma Dataplane: prometheus-server-54b6fb486d-48xc7
  Normal   Pulled                23s               kubelet                          Container image "jimmidyson/configmap-reload:v0.5.0" already present on machine
  Normal   Started               23s               kubelet                          Started container prometheus-server-configmap-reload
  Normal   Created               23s               kubelet                          Created container prometheus-server-configmap-reload
  Normal   Pulled                22s               kubelet                          Container image "docker.io/kumahq/kuma-dp:1.2.2" already present on machine
  Normal   Started               22s               kubelet                          Started container kuma-sidecar
  Normal   Created               22s               kubelet                          Created container kuma-prometheus-sd
  Normal   Created               22s               kubelet                          Created container kuma-sidecar
  Normal   Pulled                22s               kubelet                          Container image "docker.io/kumahq/kuma-prometheus-sd:1.2.2" already present on machine
  Normal   Started               22s               kubelet                          Started container kuma-prometheus-sd
  Warning  Unhealthy             21s               kubelet                          Readiness probe failed: Get "http://10.244.0.40:9901/ready": dial tcp 10.244.0.40:9901: connect: connection refused
  Normal   Created               6s (x3 over 23s)  kubelet                          Created container prometheus-server
  Normal   Started               6s (x3 over 22s)  kubelet                          Started container prometheus-server
  Normal   Pulled                6s (x3 over 23s)  kubelet                          Container image "prom/prometheus:v2.27.1" already present on machine
  Normal   UpdatedKumaDataplane  5s (x6 over 23s)  k8s.kuma.io/dataplane-generator  Updated Kuma Dataplane: prometheus-server-54b6fb486d-48xc7
  Warning  BackOff               5s (x3 over 21s)  kubelet                          Back-off restarting failed container
[root@iaas-dev0010 ~]# 
- Configuration
- Platform and Operating System
 [root@iaas-dev0010 ~]# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 8.3.2011
Release:        8.3.2011
Codename:       n/a
- Installation Method (Helm, kumactl, AWS CloudFormation, etc.)
kumactl install metrics | kubectl apply -f -
```

**Comment by RedBoneZhang** [comment]
`[root@iaas-dev0010 ~]# kumactl inspect dataplanes | grep prometheus-server
default   prometheus-server-54b6fb486d-48xc7.kuma-metrics               app=prometheus component=server kuma.io/protocol=tcp kuma.io/service=prometheus-server_kuma-metrics_svc_80 pod-template-hash=54b6fb486d                                                                                                                                             Offline   11m                  10m                3               0              10m                    2021-07-30 14:26:44   1                    1.2.2             1.18.3          inbound[port=9090,svc=prometheus-server_kuma-metrics_svc_80] is not ready`

**Comment by RedBoneZhang** [comment]
[root@iaas-dev0010 ~]# kubectl get pod -n kuma-metrics                                              
NAME                                             READY   STATUS             RESTARTS   AGE
grafana-7875d6d77f-zvbr8                         2/2     Running            0          4h27m
prometheus-alertmanager-9955cbc54-dlhqc          3/3     Running            0          4h27m
prometheus-kube-state-metrics-5ddc7b5dfd-ssk2j   2/2     Running            2          4h27m
prometheus-node-exporter-ccwd8                   1/1     Running            0          4h27m
prometheus-pushgateway-5df994c7ff-bczqm          2/2     Running            0          4h27m
prometheus-server-54b6fb486d-48xc7               3/4     CrashLoopBackOff   12         36m

**Comment by jpeach** [comment]
@RedBoneZhang can you please post the logs from the `prometheus-server-54b6fb486d-48xc7` pod? That probably has a clue to the reason the pod isn't starting.

**Comment by RedBoneZhang** [comment]
> @RedBoneZhang can you please post the logs from the `prometheus-server-54b6fb486d-48xc7` pod? That probably has a clue to the reason the pod isn't starting.

```bash
[root@iaas-dev0010 download]# kubectl logs  prometheus-server-54b6fb486d-pgx7m -n kuma-metrics -c prometheus-server 
level=info ts=2021-07-30T01:10:14.440Z caller=main.go:426 msg="Starting Prometheus" version="(version=2.27.1, branch=HEAD, revision=db7f0bcec27bd8aeebad6b08ac849516efa9ae02)"
level=info ts=2021-07-30T01:10:14.440Z caller=main.go:431 build_context="(go=go1.16.4, user=root@fd804fbd4f25, date=20210518-14:17:54)"
level=info ts=2021-07-30T01:10:14.440Z caller=main.go:432 host_details="(Linux 4.18.0-240.10.1.el8_3.x86_64 #1 SMP Mon Jan 18 17:05:51 UTC 2021 x86_64 prometheus-server-54b6fb486d-pgx7m (none))"
level=info ts=2021-07-30T01:10:14.440Z caller=main.go:433 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2021-07-30T01:10:14.440Z caller=main.go:434 vm_limits="(soft=unlimited, hard=unlimited)"
level=error ts=2021-07-30T01:10:14.441Z caller=query_logger.go:87 component=activeQueryTracker msg="Error opening query log file" file=/data/queries.active err="open /data/queries.active: permission denied"
panic: Unable to create mmap-ed active query log

goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker(0x7ffe21da5870, 0x5, 0x14, 0x3652100, 0xc0005fc660, 0x3652100)
        /app/promql/query_logger.go:117 +0x4e8
main.main()
        /app/cmd/prometheus/main.go:462 +0x58b0
```

**Comment by RedBoneZhang** [comment]
> @RedBoneZhang can you please post the logs from the `prometheus-server-54b6fb486d-48xc7` pod? That probably has a clue to the reason the pod isn't starting.

```
2021-07-30T01:07:17.209Z        ERROR   kuma-prometheus-sd.run.xds_sd.discoverer        xDS stream terminated with an error   {"streamID": 5009, "error": "failed to start an xDS stream: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 10.1.168.44:5676: connect: connection refused\"", "errorVerbose": "rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 10.1.168.44:5676: connect: connection refused\"\nfailed to start an xDS stream\ngithub.com/kumahq/kuma/app/kuma-prometheus-sd/pkg/discovery/xds/v1.(*streamDiscoverer).Run\n\t/home/circleci/project/app/kuma-prometheus-sd/pkg/discovery/xds/v1/stream.go:56\ngithub.com/kumahq/kuma/app/kuma-prometheus-sd/pkg/discovery/xds.(*discoverer).Run.func1\n\t/home/circleci/project/app/kuma-prometheus-sd/pkg/discovery/xds/xds.go:61\nruntime.goexit\n\t/home/circleci/go/src/runtime/asm_amd64.s:1371"}
```

**Comment by RedBoneZhang** [comment]
This issue has resoved by https://github.com/prometheus/prometheus/issues/5976.

**Comment by RedBoneZhang** [comment]
Resolved method  of mine:

set chmod -R 0777 [the pv mount hostpath].

**Comment by jpeach** [comment]
thanks for the update @RedBoneZhang
