### ISSUE TITLE
Logging Causes Panic - odd number of key-value pairs

### ISSUE THREAD

**Issue by jamesdbloom** [kumahq/kuma#2594]
### Summary

When there is a connection failure the logging of usage stats causes kuma-cp process to PANIC and exit.

### Steps To Reproduce

It's too complex to understand what the steps are?

We can see there is a connection failure from kuma-cp (in universal mode on EC2) which then impacts the stats reporting and causes the logging code to panic and stop the kuma-cp process as per the logs below.

### Additional Details & Logs

- Version

Kuma: 1.2.3

- Logs

```
Aug 18 09:58:06 ip-10-4-3-96.eu-west-1.compute.internal kuma-cp[75154]: 2021-08-18T09:58:06.203Z        DPANIC        core.reports        odd number of arguments passed as key-value pairs for 
logging        {"ignored key": "dial tcp 34.233.69.182:61831: connect: connection timed out"}
Aug 18 09:58:06 ip-10-4-3-96.eu-west-1.compute.internal kuma-cp[75154]: github.com/go-logr/zapr.(*infoLogger).Info
Aug 18 09:58:06 ip-10-4-3-96.eu-west-1.compute.internal kuma-cp[75154]:         /home/circleci/.go_workspace/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:70
Aug 18 09:58:06 ip-10-4-3-96.eu-west-1.compute.internal kuma-cp[75154]: github.com/kumahq/kuma/pkg/core/runtime/reports.startReportTicker.func1
Aug 18 09:58:06 ip-10-4-3-96.eu-west-1.compute.internal kuma-cp[75154]:         /home/circleci/project/pkg/core/runtime/reports/reports.go:179
Aug 18 09:58:06 ip-10-4-3-96.eu-west-1.compute.internal kuma-cp[75154]: panic: odd number of arguments passed as key-value pairs for logging
Aug 18 09:58:06 ip-10-4-3-96.eu-west-1.compute.internal kuma-cp[75154]: goroutine 150 [running]:
Aug 18 09:58:06 ip-10-4-3-96.eu-west-1.compute.internal kuma-cp[75154]: go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc000e37500, 0xc001608600, 0x1, 0x1)
Aug 18 09:58:06 ip-10-4-3-96.eu-west-1.compute.internal kuma-cp[75154]:         /home/circleci/.go_workspace/pkg/mod/go.uber.org/zap@v1.17.0/zapcore/entry.go:234 +0x58d
Aug 18 09:58:06 ip-10-4-3-96.eu-west-1.compute.internal kuma-cp[75154]: go.uber.org/zap.(*Logger).DPanic(0xc0000bb540, 0x27dde10, 0x3d, 0xc001608600, 0x1, 0x1)
Aug 18 09:58:06 ip-10-4-3-96.eu-west-1.compute.internal kuma-cp[75154]:         /home/circleci/.go_workspace/pkg/mod/go.uber.org/zap@v1.17.0/logger.go:217 +0x85
Aug 18 09:58:06 ip-10-4-3-96.eu-west-1.compute.internal kuma-cp[75154]: github.com/go-logr/zapr.handleFields(0xc0000bb540, 0xc0015e9cf0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x10, 0x21f2960, 0x33aac01)
Aug 18 09:58:06 ip-10-4-3-96.eu-west-1.compute.internal kuma-cp[75154]:         /home/circleci/.go_workspace/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:106 +0x5e5
Aug 18 09:58:06 ip-10-4-3-96.eu-west-1.compute.internal kuma-cp[75154]: github.com/go-logr/zapr.(*infoLogger).Info(0xc0015e9ce0, 0x2787bf5, 0x19, 0xc0015e9cf0, 0x1, 0x1)
Aug 18 09:58:06 ip-10-4-3-96.eu-west-1.compute.internal kuma-cp[75154]:         /home/circleci/.go_workspace/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:70 +0xb1
Aug 18 09:58:06 ip-10-4-3-96.eu-west-1.compute.internal kuma-cp[75154]: github.com/kumahq/kuma/pkg/core/runtime/reports.startReportTicker.func1(0xc000d02240, 0x3405628, 0xc000971920)
Aug 18 09:58:06 ip-10-4-3-96.eu-west-1.compute.internal kuma-cp[75154]:         /home/circleci/project/pkg/core/runtime/reports/reports.go:179 +0x31e
Aug 18 09:58:06 ip-10-4-3-96.eu-west-1.compute.internal kuma-cp[75154]: created by github.com/kumahq/kuma/pkg/core/runtime/reports.startReportTicker
Aug 18 09:58:06 ip-10-4-3-96.eu-west-1.compute.internal kuma-cp[75154]:         /home/circleci/project/pkg/core/runtime/reports/reports.go:176 +0x53
Aug 18 09:58:06 ip-10-4-3-96.eu-west-1.compute.internal systemd[1]: kuma-cp.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 18 09:58:06 ip-10-4-3-96.eu-west-1.compute.internal systemd[1]: kuma-cp.service: Failed with result 'exit-code'.
Aug 18 09:58:07 ip-10-4-3-96.eu-west-1.compute.internal systemd[1]: kuma-cp.service: Service RestartSec=1s expired, scheduling restart.
Aug 18 09:58:07 ip-10-4-3-96.eu-west-1.compute.internal systemd[1]: kuma-cp.service: Scheduled restart job, restart counter is at 442.
Aug 18 09:58:07 ip-10-4-3-96.eu-west-1.compute.internal systemd[1]: Stopped Kuma Control Plane in Universal mode.
Aug 18 09:58:07 ip-10-4-3-96.eu-west-1.compute.internal systemd[1]: Started Kuma Control Plane in Universal mode.
```

- Configuration

```
[centos@ip-10-4-18-32 ~]$ cat /etc/systemd/system/kuma-cp.service
[Unit]
Description=Kuma Control Plane in Universal mode
After=network.target
Documentation=https://kuma.io

[Service]
Type=simple
Environment=KUMA_GENERAL_WORK_DIR=/etc/kuma
Environment=KUMA_MODE=zone
Environment=KUMA_MULTIZONE_ZONE_NAME=ec2
Environment=KUMA_MULTIZONE_ZONE_GLOBAL_ADDRESS=grpcs://kuma-global-zone-aks.dev.<redacted>.com:5685
ExecStart=/usr/bin/kuma-cp run --log-level debug
KillMode=process
Restart=on-failure
RestartSec=1
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
```

- Platform and Operating System

EC2, CentOS 8

- Installation Method (Helm, kumactl, AWS CloudFormation, etc.)

manual via systemctl, see above for service definition

**Comment by jakubdyszkiewicz** [comment]
Hey, thanks for reporting it. Please set `kuma_reports_enabled` to `false` as a workaround for current version.

**Comment by jamesdbloom** [comment]
Ok will do.

It looks like we need to allow calls to the `kong-hf.konghq.com` to our security group to remove this error, because I can see that domain name resolves to the IP which it is failing to talk to.

I assume this host is gathering usage statistics, is that correct?

**Comment by lahabana** [comment]
This seems to be only the case with `--log-level debug`. If you remove it this problem won't happen.

Root cause: The debug logs set the `zap.Development()` flag which causes panic on `DPanic` level logs (which this imbalance log is).

**Comment by jamesdbloom** [comment]
Ok that makes sense and we have fixed it for now with the `KUMA_REPORTS_ENABLED` to `false` as suggested by @jakubdyszkiewicz .

I guess it would still be nice to be able to set the `--log-level debug` and not disable reporting.

**Comment by lahabana** [comment]
Of course and we'll fix that! (Just wanted to provide a workaround).
