### ISSUE TITLE
Panic when trying to unmarshal incorrect policy 

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma#4293]
### What happened?

Trying to apply a TrafficRoute (although would happen on any policy) with an integer in a string field resulted in a panic in the validator:

```
2022/05/16 16:36:18 http: panic serving 10.42.0.0:16792: failed to unmarshal *v1alpha1.TrafficRoute: json: cannot unmarshal number into Go value of type string goroutine 821544 [running]: net/http.(*conn).serve.func1() /home/circleci/go/src/net/http/server.go:1802 +0xb9 panic({0x2305820, 0xc00262d020}) /home/circleci/go/src/runtime/panic.go:1047 +0x266 github.com/kumahq/kuma/pkg/util/proto.MustUnmarshalJSON({0xc002971da6, 0xc000d53ec0, 0x40d2c7}, {0x3b6c6e0, 0xc000c20720}) /home/circleci/.go_workspace/pkg/mod/github.com/kumahq/kuma@v0.0.0-20220411101831-653f19867b50/pkg/util/proto/proto.go:67 +0xc8 github.com/kumahq/kuma/pkg/plugins/resources/k8s/native/api/v1alpha1.(*TrafficRoute).GetSpec(0xc002971800) /home/circleci/.go_workspace/pkg/mod/github.com/kumahq/kuma@v0.0.0-20220411101831-653f19867b50/pkg/plugins/resources/k8s/native/api/v1alpha1/zz_generated.mesh.go:1651 +0x58 github.com/kumahq/kuma/pkg/plugins/resources/k8s.(*SimpleConverter).ToCoreResource(0xc002afa0f0, {0x3c1299 ...
```

Need to catch this and surface it gracefully.

**Comment by michaelbeaumont** [comment]
I believe this is already fixed by https://github.com/kumahq/kuma/pull/4455
