### ISSUE TITLE
Kuma Zonal CP offline - invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by brunda-bs** [kumahq/kuma#4816]
### What happened?

Hi,
Kuma Zonal CPs are getting frequently disconnected from the Global CP. 

<img width="1300" alt="Screenshot 2022-08-12 at 3 38 02 PM" src="https://user-images.githubusercontent.com/97163498/184333205-0f552fe9-6fb3-4cdf-aa50-494d195f3e4c.png">

Below are the Kuma zonal cp pod log:
```
I0812 09:54:54.577117       1 request.go:665] Waited for 1.002918158s due to client-side throttling, not priority and fairness, request: GET:https://10.1.0.1:443/apis/helm.toolkit.fluxcd.io/v2beta1?timeout=32s
2022-08-12T09:54:55.381Z	INFO	controller-runtime.webhook	Registering webhook	{"path": "/validate-kuma-io-v1alpha1"}
2022-08-12T09:54:55.381Z	INFO	controller-runtime.webhook	Registering webhook	{"path": "/validate-v1-service"}
2022-08-12T09:54:55.381Z	INFO	controller-runtime.webhook	Registering webhook	{"path": "/validate-v1-secret"}
2022-08-12T09:54:58.330Z	INFO	controller-runtime.webhook	Registering webhook	{"path": "/inject-sidecar"}
2022-08-12T09:54:58.330Z	INFO	controller-runtime.webhook	Registering webhook	{"path": "/owner-reference-kuma-io-v1alpha1"}
2022-08-12T09:54:58.330Z	INFO	plugin.runtime.k8s	Registering a defaulting webhook	{"GVK": "kuma.io/v1alpha1, Kind=Mesh", "path": "/default-kuma-io-v1alpha1-mesh"}
2022-08-12T09:54:58.330Z	INFO	controller-runtime.webhook	Registering webhook	{"path": "/default-kuma-io-v1alpha1-mesh"}
2022-08-12T09:54:58.333Z	INFO	kuma-cp.run	Current config {"access":{"static":{"adminResources":{"groups":["mesh-system:admin"],"users":["mesh-system:admin"]},"generateDpToken":{"groups":["mesh-system:admin"],"users":["mesh-system:admin"]},"generateUserToken":{"groups":["mesh-system:admin"],"users":["mesh-system:admin"]},"generateZoneToken":{"groups":["mesh-system:admin"],"users":["mesh-system:admin"]},"viewConfigDump":{"groups":["mesh-system:unauthenticated","mesh-system:authenticated"],"users":[]}},"type":"static"},"apiServer":{"auth":{"clientCertsDir":""},"authn":{"localhostIsAdmin":false,"tokens":{"bootstrapAdminToken":true},"type":"tokens"},"corsAllowedDomains":[".*"],"http":{"enabled":true,"interface":"0.0.0.0","port":5681},"https":{"enabled":true,"interface":"0.0.0.0","port":5682,"tlsCertFile":"/var/run/secrets/kuma.io/tls-cert/tls.crt","tlsKeyFile":"/var/run/secrets/kuma.io/tls-cert/tls.key"},"readOnly":true},"bootstrapServer":{"params":{"adminAccessLogPath":"/dev/null","adminAddress":"127.0.0.1","adminPort":9901,"xdsConnectTimeout":"1s","xdsHost":"","xdsPort":5678}},"defaults":{"skipMeshCreation":false},"diagnostics":{"debugEndpoints":false,"serverPort":5680},"dnsServer":{"CIDR":"240.0.0.0/4","domain":"mesh","port":5653,"serviceVipEnabled":true},"dpServer":{"auth":{"type":"serviceAccountToken"},"hds":{"checkDefaults":{"healthyThreshold":1,"interval":"1s","noTrafficInterval":"1s","timeout":"2s","unhealthyThreshold":1},"enabled":false,"interval":"5s","refreshInterval":"10s"},"port":5678,"tlsCertFile":"/var/run/secrets/kuma.io/tls-cert/tls.crt","tlsKeyFile":"/var/run/secrets/kuma.io/tls-cert/tls.key"},"environment":"kubernetes","experimental":{"gatewayAPI":false,"kubeOutboundsAsVIPs":false,"meshGateway":false},"general":{"dnsCacheTTL":"10s","tlsCertFile":"/var/run/secrets/kuma.io/tls-cert/tls.crt","tlsKeyFile":"/var/run/secrets/kuma.io/tls-cert/tls.key","workDir":"/home/kuma-cp/.kuma"},"guiServer":{"apiServerUrl":""},"metrics":{"dataplane":{"idleTimeout":"5m0s","subscriptionLimit":2},"mesh":{"maxResyncTimeout":"20s","minResyncTimeout":"1s"},"zone":{"idleTimeout":"5m0s","subscriptionLimit":10}},"mode":"zone","monitoringAssignmentServer":{"apiVersions":["v1"],"assignmentRefreshInterval":"1s","defaultFetchTimeout":"30s","grpcPort":0,"port":5676},"multizone":{"global":{"kds":{"grpcPort":5685,"maxMsgSize":10485760,"refreshInterval":"1s","tlsCertFile":"/var/run/secrets/kuma.io/tls-cert/tls.crt","tlsKeyFile":"/var/run/secrets/kuma.io/tls-cert/tls.key","zoneInsightFlushInterval":"10s"}},"zone":{"globalAddress":"grpcs://global-zone-sync-cdt.maersk-digital.net:443","kds":{"maxMsgSize":10485760,"refreshInterval":"1s","rootCaFile":""},"name":"ohp-np-west-1"}},"reports":{"enabled":false},"runtime":{"kubernetes":{"admissionServer":{"address":"","certDir":"/var/run/secrets/kuma.io/tls-cert","port":5443},"controlPlaneServiceName":"kuma-control-plane","injector":{"builtinDNS":{"enabled":true,"port":15053},"caCertFile":"/var/run/secrets/kuma.io/tls-cert/ca.crt","cniEnabled":true,"exceptions":{"labels":{"openshift.io/build.name":"*","openshift.io/deployer-pod-for.name":"*"}},"initContainer":{"image":"mskmeshsharedgcore.azurecr.io/kumahq/kuma-init:1.6.0"},"sidecarContainer":{"drainTime":"30s","envVars":{},"gid":5678,"image":"mskmeshsharedgcore.azurecr.io/kumahq/kuma-dp:1.6.0","livenessProbe":{"failureThreshold":12,"initialDelaySeconds":60,"periodSeconds":5,"timeoutSeconds":3},"readinessProbe":{"failureThreshold":12,"initialDelaySeconds":1,"periodSeconds":5,"successThreshold":1,"timeoutSeconds":3},"redirectPortInbound":15006,"redirectPortInboundV6":15010,"redirectPortOutbound":15001,"resources":{"limits":{"cpu":"1000m","memory":"512Mi"},"requests":{"cpu":"50m","memory":"64Mi"}},"uid":5678},"sidecarTraffic":{"excludeInboundPorts":[],"excludeOutboundPorts":[]},"virtualProbesEnabled":true,"virtualProbesPort":9000},"marshalingCacheExpirationTime":"5m0s","serviceAccountName":"system:serviceaccount:kuma-system:kuma-control-plane"},"universal":{"dataplaneCleanupAge":"72h0m0s"}},"store":{"cache":{"enabled":true,"expirationTime":"1s"},"kubernetes":{"systemNamespace":"kuma-system"},"postgres":{"connectionTimeout":5,"dbName":"kuma","host":"127.0.0.1","maxIdleConnections":50,"maxOpenConnections":50,"maxReconnectInterval":"1m0s","minReconnectInterval":"10s","password":"*****","port":15432,"tls":{"caPath":"","certPath":"","keyPath":"","mode":"disable"},"user":"kuma"},"type":"kubernetes","upsert":{"conflictRetryBaseBackoff":"100ms","conflictRetryMaxTimes":5}},"xdsServer":{"dataplaneConfigurationRefreshInterval":"1m0s","dataplaneStatusFlushInterval":"1m0s","nackBackoff":"5s"}}
2022-08-12T09:54:58.333Z	INFO	kuma-cp.run	Running in mode `zone`
2022-08-12T09:54:58.333Z	INFO	mads-server	MADS v1 is enabled
2022-08-12T09:54:59.428Z	INFO	xds-server	registering Aggregated Discovery Service V3 in Dataplane Server
2022-08-12T09:54:59.428Z	INFO	bootstrap	registering Bootstrap in Dataplane Server
2022-08-12T09:54:59.523Z	INFO	kuma-cp.run	starting Control Plane	{"version": "1.6.0"}
2022-08-12T09:54:59.523Z	INFO	controller-runtime.webhook.webhooks	Starting webhook server
2022-08-12T09:54:59.523Z	INFO	controller-runtime.certwatcher	Updated current TLS certificate
2022-08-12T09:54:59.523Z	INFO	dns-server	starting	{"address": "0.0.0.0:5653"}
2022-08-12T09:54:59.523Z	INFO	controller-runtime.certwatcher	Starting certificate watcher
2022-08-12T09:54:59.523Z	INFO	dp-server	starting	{"interface": "0.0.0.0", "port": 5678, "tls": true}
2022-08-12T09:54:59.523Z	INFO	api-server	starting	{"interface": "0.0.0.0", "port": 5681}
2022-08-12T09:54:59.523Z	INFO	api-server	starting	{"interface": "0.0.0.0", "port": 5682, "tls": true}
2022-08-12T09:54:59.523Z	INFO	dns-vips-synchronizer	starting the DNS VIPs Synchronizer
2022-08-12T09:54:59.523Z	INFO	leader	Trying to become the leader.
2022-08-12T09:54:59.523Z	INFO	xds-server.diagnostics	starting diagnostic server	{"interface": "0.0.0.0", "port": 5680}
2022-08-12T09:54:59.523Z	INFO	controller-runtime.webhook	Serving webhook server	{"host": "", "port": 5443}
2022-08-12T09:54:59.524Z	INFO	mads-server	starting	{"interface": "0.0.0.0", "port": 5676}
2022-08-12T09:55:00.625Z	INFO	clusterID	setting cluster ID	{"clusterID": "97a475a2-6832-4a27-93c5-9679635c8721"}
2022-08-12T09:55:01.392Z	INFO	leader	Found existing lock	{"LockOwner": "kuma-control-plane-5567x4db98-nrrkp"}
2022-08-12T09:55:01.786Z	INFO	leader	Not the leader. Waiting.
2022-08-12T09:55:03.262Z	INFO	leader	Not the leader. Waiting.
2022-08-12T09:55:05.643Z	INFO	leader	Not the leader. Waiting.
2022-08-12T09:55:08.160Z	INFO	bootstrap	Generating bootstrap config	{"params": {"Id":".kuma-egress-7b69fd67db-smgq8.kuma-system","Service":"egress","AdminAddress":"127.0.0.1","AdminPort":9901,"AdminAccessLogPath":"/dev/null","XdsHost":"kuma-control-plane.kuma-system","XdsPort":5678,"XdsConnectTimeout":1000000000,"AccessLogPipe":"/tmp/kuma-al-kuma-egress-7b69fd67db-smgq8.kuma-system-.sock","DataplaneToken":"***","DataplaneResource":"","CertBytes":"***","KumaDpVersion":"1.6.0","KumaDpGitTag":"1.6.0","KumaDpGitCommit":"*","KumaDpBuildDate":"2022-04-20T19:32:20Z","EnvoyVersion":"1.21.1","EnvoyBuild":"af50070ee60866874b0a9383daf9364e884ded22/1.21.1/Clean/RELEASE/BoringSSL","EnvoyKumaDpCompatible":true,"HdsEnabled":false,"DynamicMetadata":{},"DNSPort":15054,"EmptyDNSPort":15055,"ProxyType":"egress"}}
2022-08-12T09:55:10.330Z	INFO	leader	Not the leader. Waiting.
2022-08-12T09:55:19.058Z	INFO	leader	Not the leader. Waiting.
2022-08-12T09:55:36.265Z	INFO	leader	Not the leader. Waiting.
2022-08-12T09:55:54.732Z	INFO	leader	Not the leader. Waiting.
2022-08-12T09:56:13.051Z	INFO	xds.secrets	generating certificate	{"ZoneEgress": {"Mesh":"default","Name":"kuma-egress-7b69fd67db-smgq8.kuma-system"}, "reason": "mTLS is enabled and DP hasn't received a certificate yet"}
2022-08-12T09:56:14.522Z	INFO	leader	Not the leader. Waiting.
**panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x11bf9f5]**

goroutine 1254 [running]:
github.com/kumahq/kuma/pkg/xds/envoy/endpoints/v3.LocalityLbEndpointsMap.asSlice.func1(0x1e18d00, 0xc0017ebe18)
	/home/circleci/project/pkg/xds/envoy/endpoints/v3/endpoints.go:100 +0x55
sort.insertionSort_func({0xc004dea798, 0xc005381960}, 0x0, 0x2)
	/home/circleci/go/src/sort/zfuncversion.go:12 +0xb1
sort.quickSort_func({0xc004dea798, 0xc005381960}, 0xc0017ebe30, 0x0, 0xc0017ebe18)
	/home/circleci/go/src/sort/zfuncversion.go:158 +0x185
sort.Slice({0x1e18d40, 0xc0017ebe30}, 0x2)
	/home/circleci/go/src/sort/slice.go:20 +0x9f
github.com/kumahq/kuma/pkg/xds/envoy/endpoints/v3.LocalityLbEndpointsMap.asSlice(0xc004dea8d8)
	/home/circleci/project/pkg/xds/envoy/endpoints/v3/endpoints.go:98 +0x1c5
github.com/kumahq/kuma/pkg/xds/envoy/endpoints/v3.CreateClusterLoadAssignment({0xc004850f80, 0x32}, {0xc0052e1710, 0x2, 0x1f6e300})
	/home/circleci/project/pkg/xds/envoy/endpoints/v3/endpoints.go:62 +0x152
github.com/kumahq/kuma/pkg/xds/envoy/endpoints.CreateClusterLoadAssignment(...)
	/home/circleci/project/pkg/xds/envoy/endpoints/endpoints.go:16
github.com/kumahq/kuma/pkg/xds/generator/egress.(*InternalServicesGenerator).generateEDS(0xc0001160d0, {0xc0049b0356, 0x7}, {0x23aeabc, 0x2}, 0xc004deac50, 0x2)
	/home/circleci/project/pkg/xds/generator/egress/internal_services_generator.go:72 +0x1d0
github.com/kumahq/kuma/pkg/xds/generator/egress.(*InternalServicesGenerator).Generate(0x412bf9, {0xc001125c00, {{0x0, 0x0}, 0x0, 0x0, 0x0, 0x0, {0x0, 0x0, ...}, ...}}, ...)
	/home/circleci/project/pkg/xds/generator/egress/internal_services_generator.go:48 +0x218
github.com/kumahq/kuma/pkg/xds/generator/egress.Generator.Generate({{0xc0005ce280, 0x2000100, 0x0}}, {0xc001125c00, {{0x0, 0x0}, 0x0, 0x0, 0x0, 0x0, ...}}, ...)
	/home/circleci/project/pkg/xds/generator/egress/generator.go:72 +0x323
github.com/kumahq/kuma/pkg/xds/generator.CompositeResourceGenerator.Generate({0xc000491d70, 0x3, 0xc004deb088}, {0xc001125c00, {{0x0, 0x0}, 0x0, 0x0, 0x0, 0x0, ...}}, ...)
	/home/circleci/project/pkg/xds/generator/resource_generator.go:19 +0x123
github.com/kumahq/kuma/pkg/xds/generator.(*ProxyTemplateProfileSource).Generate(0xc004deb1b8, {0xc001125c00, {{0x0, 0x0}, 0x0, 0x0, 0x0, 0x0, {0x0, 0x0, ...}, ...}}, ...)
	/home/circleci/project/pkg/xds/generator/proxy_template.go:71 +0x9d
github.com/kumahq/kuma/pkg/xds/generator.(*ProxyTemplateGenerator).Generate(0xc004deb370, {0xc001125c00, {{0x0, 0x0}, 0x0, 0x0, 0x0, 0x0, {0x0, 0x0, ...}, ...}}, ...)
	/home/circleci/project/pkg/xds/generator/proxy_template.go:23 +0x268
github.com/kumahq/kuma/pkg/xds/server/v3.(*templateSnapshotGenerator).GenerateSnapshot(_, {0xc001125c00, {{0x0, 0x0}, 0x0, 0x0, 0x0, 0x0, {0x0, 0x0, ...}, ...}}, ...)
	/home/circleci/project/pkg/xds/server/v3/reconcile.go:164 +0xd2
github.com/kumahq/kuma/pkg/xds/server/v3.(*reconciler).Reconcile(0xc0006c9170, {0xc001125c00, {{0x0, 0x0}, 0x0, 0x0, 0x0, 0x0, {0x0, 0x0, ...}, ...}}, ...)
	/home/circleci/project/pkg/xds/server/v3/reconcile.go:57 +0x19d
github.com/kumahq/kuma/pkg/xds/sync.(*DataplaneWatchdog).syncEgress(0xc00168dee0)
	/home/circleci/project/pkg/xds/sync/dataplane_watchdog.go:151 +0xdb
github.com/kumahq/kuma/pkg/xds/sync.(*DataplaneWatchdog).Sync(0xc00168dee0)
	/home/circleci/project/pkg/xds/sync/dataplane_watchdog.go:64 +0xc5
github.com/kumahq/kuma/pkg/xds/sync.(*dataplaneWatchdogFactory).New.func2()
	/home/circleci/project/pkg/xds/sync/dataplane_watchdog_factory.go:43 +0xa6
github.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).Start(0xc0023ae260, 0xc002198540)
	/home/circleci/project/pkg/util/watchdog/watchdog.go:25 +0xe2
created by github.com/kumahq/kuma/pkg/xds/server/callbacks.(*dataplaneSyncTracker).OnProxyConnected
	/home/circleci/project/pkg/xds/server/callbacks/dataplane_sync_tracker.go:55 +0x412
```

**Comment by jakubdyszkiewicz** [comment]
Hey, thanks for the report. I fixed the issue using unit tests although I'm having trouble reproducing it on the real Kuma system.

Can you share a little bit about your env? Do you apply external services? maybe with some `kuma.io/zone` tags?

**Comment by brunda-bs** [comment]
Hi @jakubdyszkiewicz ,

Thanks for the fix. 

Sure, We do have a couple of external services created. But with the` kuma.io/service` and `kuma.io/protocol` tags.
