### ISSUE TITLE
Kuma Zonal control plane pod frequent restarts

### ISSUE THREAD

**Issue by brunda-bs** [kumahq/kuma#5079]
### What happened?

Hi Team,

We see that Kuma zonal control plane pods are frequently restarting in the multi-zone setup on AKS.
```
NAME                                  READY   STATUS    RESTARTS           AGE
kuma-control-plane-7c55548bf6-279ch   1/1     Running   892 (9m52s ago)    7d17h
kuma-control-plane-7c55548bf6-hnmzs   1/1     Running   1211 (12m ago)     28d
kuma-control-plane-7c55548bf6-tbtl4   1/1     Running   1184 (9m15s ago)   20d
```
Here is the Zone Insight from the GUI.
<img width="1210" alt="Screenshot 2022-09-29 at 4 18 47 PM" src="https://user-images.githubusercontent.com/97163498/193012344-76d6ac5a-e7b6-4725-9481-73ca86864533.png">

Here is the logs of one of the leader pod from Zone CP.

```2022-09-29T10:41:35.324Z	INFO	outbound-proxy-generator	there is no selected TrafficRoute for the outbound interface, which means that the traffic won't be routed. Visit https://kuma.io/docs/latest/policies/traffic-route/ to check how to introduce the routing.	{"dataplane": "nginx-sm-ingress-nginx-controller-597c546c67-bxq9s.kuma-gateway", "mesh": "default", "outbound": "10.1.110.192:6379"}
2022-09-29T10:41:42.027Z	INFO	kds.reconcile	detected changes in the resources. Sending changes to the client.	{"resourceType": "DataplaneInsight", "client": "global"}
2022-09-29T10:41:42.027Z	INFO	kds.reconcile	detected changes in the resources. Sending changes to the client.	{"resourceType": "ZoneEgressInsight", "client": "global"}
2022-09-29T10:41:44.027Z	INFO	kds.reconcile	detected changes in the resources. Sending changes to the client.	{"resourceType": "DataplaneInsight", "client": "global"}
2022-09-29T10:41:44.027Z	INFO	kds.reconcile	detected changes in the resources. Sending changes to the client.	{"resourceType": "ZoneEgressInsight", "client": "global"}
2022-09-29T10:41:44.027Z	INFO	kds.reconcile	detected changes in the resources. Sending changes to the client.	{"resourceType": "ZoneIngressInsight", "client": "global"}
fatal error: concurrent map writes

goroutine 3114 [running]:
runtime.throw({0x23d013a, 0x230e680})
	/home/circleci/go/src/runtime/panic.go:1198 +0x71 fp=0xc004603820 sp=0xc0046037f0 pc=0x436d31
runtime.mapassign_faststr(0xc004603990, 0xc005b02120, {0x23b0316, 0x4})
	/home/circleci/go/src/runtime/map_faststr.go:211 +0x39c fp=0xc004603888 sp=0xc004603820 pc=0x412f3c
github.com/kumahq/kuma/pkg/xds/topology.BuildRemoteEndpointMap(0xc0048b5218, {0xc0000740d9, 0x16}, {0xc0013a4200, 0x18, 0x20}, {0x0, 0x0, 0x0}, {0x306ef40, ...})
	/home/circleci/project/pkg/xds/topology/outbound.go:68 +0x375 fp=0xc004603a00 sp=0xc004603888 pc=0x1187d35
github.com/kumahq/kuma/pkg/xds/sync.(*EgressProxyBuilder).Build(0xc0002861c0, {{0xc00621e2a0, 0x439d3c}, {0xc00621e2a1, 0xc9f065}})
	/home/circleci/project/pkg/xds/sync/egress_proxy_builder.go:104 +0x9d7 fp=0xc004603d60 sp=0xc004603a00 pc=0x1a6baf7
github.com/kumahq/kuma/pkg/xds/sync.(*DataplaneWatchdog).syncEgress(0xc00256e340)
	/home/circleci/project/pkg/xds/sync/dataplane_watchdog.go:146 +0x7e fp=0xc004603e80 sp=0xc004603d60 pc=0x1a6a83e
github.com/kumahq/kuma/pkg/xds/sync.(*DataplaneWatchdog).Sync(0xc00256e340)
	/home/circleci/project/pkg/xds/sync/dataplane_watchdog.go:64 +0xc5 fp=0xc004603ec0 sp=0xc004603e80 pc=0x1a69ea5
github.com/kumahq/kuma/pkg/xds/sync.(*dataplaneWatchdogFactory).New.func2()
	/home/circleci/project/pkg/xds/sync/dataplane_watchdog_factory.go:43 +0xa6 fp=0xc004603f30 sp=0xc004603ec0 pc=0x1a6afc6
github.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).Start(0xc003caa840, 0xc0030b40c0)
	/home/circleci/project/pkg/util/watchdog/watchdog.go:25 +0xe2 fp=0xc004603fc0 sp=0xc004603f30 pc=0x116ba22
github.com/kumahq/kuma/pkg/xds/server/callbacks.(*dataplaneSyncTracker).OnProxyConnected·dwrap·17()
	/home/circleci/project/pkg/xds/server/callbacks/dataplane_sync_tracker.go:55 +0x2f fp=0xc004603fe0 sp=0xc004603fc0 pc=0x1a6124f
runtime.goexit()
	/home/circleci/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc004603fe8 sp=0xc004603fe0 pc=0x46aa01
created by github.com/kumahq/kuma/pkg/xds/server/callbacks.(*dataplaneSyncTracker).OnProxyConnected
	/home/circleci/project/pkg/xds/server/callbacks/dataplane_sync_tracker.go:55 +0x412

goroutine 1 [semacquire, 5 minutes]:
sync.runtime_Semacquire(0xc0000001a0)
	/home/circleci/go/src/runtime/sema.go:56 +0x25
sync.(*WaitGroup).Wait(0xc000d0b230)
	/home/circleci/go/src/sync/waitgroup.go:130 +0x71
golang.org/x/sync/errgroup.(*Group).Wait(0xc000ee3260)
	/home/circleci/.go_workspace/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:40 +0x27
github.com/kumahq/kuma/pkg/plugins/bootstrap/k8s.(*kubeComponentManager).Start(0xc00093f0b0, 0xc000703ce0)
	/home/circleci/project/pkg/plugins/bootstrap/k8s/plugin.go:360 +0x1dc
github.com/kumahq/kuma/app/kuma-cp/cmd.newRunCmdWithOpts.func1(0xc000b12c80, {0x23b021e, 0x2, 0x2})
	/home/circleci/project/app/kuma-cp/cmd/run.go:180 +0xeb7
github.com/spf13/cobra.(*Command).execute(0xc000b12c80, {0xc000251e80, 0x2, 0x2})
	/home/circleci/.go_workspace/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000b12a00)
	/home/circleci/.go_workspace/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/circleci/.go_workspace/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/kumahq/kuma/app/kuma-cp/cmd.Execute()
	/home/circleci/project/app/kuma-cp/cmd/root.go:86 +0x1e
main.main()
	/home/circleci/project/app/kuma-cp/main.go:6 +0x17

goroutine 1287 [sync.Cond.Wait, 4 minutes]:
sync.runtime_notifyListWait(0xc0008ce988, 0x1)
	/home/circleci/go/src/runtime/sema.go:513 +0x13d
sync.(*Cond).Wait(0xc0009e2880)
	/home/circleci/go/src/sync/cond.go:56 +0x8c
k8s.io/client-go/tools/cache.(*DeltaFIFO).Pop(0xc0008ce960, 0xc001844060)
	/home/circleci/.go_workspace/pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/delta_fifo.go:527 +0x233
k8s.io/client-go/tools/cache.(*controller).processLoop(0xc000e9a2d0)
	/home/circleci/.go_workspace/pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/controller.go:183 +0x36
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f24198d5650)
	/home/circleci/.go_workspace/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x1895f68, {0x30722e0, 0xc00148e240}, 0x1, 0xc000e1dda0)
	/home/circleci/.go_workspace/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000e9a338, 0x3b9aca00, 0x0, 0x0, 0x7f2419a1c570)
	/home/circleci/.go_workspace/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/home/circleci/.go_workspace/pkg/mod/k8s.io/apimachinery@v0.23.5/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*controller).Run(0xc000e9a2d0, 0xc000e1dda0)
	/home/circleci/.go_workspace/pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/controller.go:154 +0x2fb
k8s.io/client-go/tools/cache.(*sharedIndexInformer).Run(0xc000cb3900, 0xc00009c7b8)
	/home/circleci/.go_workspace/pkg/mod/k8s.io/client-go@v0.23.5/tools/cache/shared_informer.go:414 +0x498
created by github.com/kumahq/kuma/pkg/plugins/bootstrap/k8s/cache/internal.(*specificInformersMap).addInformerToMap
	/home/circleci/project/pkg/plugins/bootstrap/k8s/cache/internal/informers_map.go:223 +0x425

goroutine 7 [chan receive]:
k8s.io/klog/v2.(*loggingT).flushDaemon(0x0)
	/home/circleci/.go_workspace/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:1181 +0x6a
created by k8s.io/klog/v2.init.0
	/home/circleci/.go_workspace/pkg/mod/k8s.io/klog/v2@v2.30.0/klog.go:420 +0xfb

goroutine 62 [IO wait]:
internal/poll.runtime_pollWait(0x7f2419c194d8, 0x72)
	/home/circleci/go/src/runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0xc000bbc680, 0xc00134e000, 0x0)
	/home/circleci/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/home/circleci/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000bbc680, {0xc00134e000, 0xb5f5, 0xb5f5})
	/home/circleci/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc000bbc680, {0xc00134e000, 0xc00134f336, 0x913})
	/home/circleci/go/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc0002632e8, {0xc00134e000, 0x6, 0xc0020e97f0})
	/home/circleci/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc006208030, {0xc00134e000, 0x0, 0x409cad})
	/home/circleci/go/src/crypto/tls/conn.go:777 +0x3d
bytes.(*Buffer).ReadFrom(0xc0005fa278, {0x305ae20, 0xc006208030})
	/home/circleci/go/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc0005fa000, {0x3072660, 0xc0002632e8}, 0xa2c4)
	/home/circleci/go/src/crypto/tls/conn.go:799 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc0005fa000, 0x0)
	/home/circleci/go/src/crypto/tls/conn.go:606 +0x112
crypto/tls.(*Conn).readRecord(...)
	/home/circleci/go/src/crypto/tls/conn.go:574
crypto/tls.(*Conn).Read(0xc0005fa000, {0xc000a20000, 0x1000, 0x913800})
	/home/circleci/go/src/crypto/tls/conn.go:1277 +0x16f
bufio.(*Reader).Read(0xc0008b8180, {0xc000ac03c0, 0x9, 0x921662})
	/home/circleci/go/src/bufio/bufio.go:227 +0x1b4
io.ReadAtLeast({0x305abc0, 0xc0008b8180}, {0xc000ac03c0, 0x9, 0x9}, 0x9)
	/home/circleci/go/src/io/io.go:328 +0x9a
io.ReadFull(...)
	/home/circleci/go/src/io/io.go:347
golang.org/x/net/http2.readFrameHeader({0xc000ac03c0, 0x9, 0xc0011e2030}, {0x305abc0, 0xc0008b8180})
	/home/circleci/.go_workspace/pkg/mod/golang.org/x/net@v0.0.0-20220225172249-27dd8689420f/http2/frame.go:237 +0x6e
golang.org/x/net/http2.(*Framer).ReadFrame(0xc000ac0380)
	/home/circleci/.go_workspace/pkg/mod/golang.org/x/net@v0.0.0-20220225172249-27dd8689420f/http2/frame.go:498 +0x95
golang.org/x/net/http2.(*clientConnReadLoop).run(0xc0020e9f98)
	/home/circleci/.go_workspace/pkg/mod/golang.org/x/net@v0.0.0-20220225172249-27dd8689420f/http2/transport.go:2118 +0x130
golang.org/x/net/http2.(*ClientConn).readLoop(0xc0001ea780)
	/home/circleci/.go_workspace/pkg/mod/golang.org/x/net@v0.0.0-20220225172249-27dd8689420f/http2/transport.go:2014 +0x6f
created by golang.org/x/net/http2.(*Transport).newClientConn
	/home/circleci/.go_workspace/pkg/mod/golang.org/x/net@v0.0.0-20220225172249-27dd8689420f/http2/transport.go:725 +0xac5```

**Comment by bartsmykla** [comment]
Hi @brunda-bs, I'm almost certain it's the same problem we fixed yesterday at https://github.com/kumahq/kuma/pull/5070
It will be released in a patch release next week

**Comment by brunda-bs** [comment]
Hi @bartsmykla,

When can we expect kuma 1.6.2 helm chart?

I see tag has been released 13 hours ago.

% helm search repo kuma -l
NAME   	CHART VERSION	APP VERSION	DESCRIPTION
kuma/kuma	1.8.0    	1.8.0   	A Helm chart for the Kuma Control Plane
kuma/kuma	1.7.1    	1.7.1   	A Helm chart for the Kuma Control Plane
kuma/kuma	1.7.0    	1.7.0   	A Helm chart for the Kuma Control Plane
kuma/kuma	1.6.1    	1.6.1   	A Helm chart for the Kuma Control Plane
kuma/kuma	1.6.0    	1.6.0   	A Helm chart for the Kuma Control Plane
kuma/kuma	0.9.2    	1.5.2   	A Helm chart for the Kuma Control Plane

**Comment by lahabana** [comment]
I think @lobkovilya is pushing the new helm charts

**Comment by lahabana** [comment]
@brunda-bs the release is out can you confirm whether the problem is fixed?

**Comment by brunda-bs** [comment]
HI @lahabana ,

Yes, I see the issue is fixed now. Thanks!

**Comment by lahabana** [comment]
Thanks for confirming!
