### ISSUE TITLE
External Service with kafka protocol is not working 

### ISSUE THREAD

**Issue by adarsh-padhi** [kumahq/kuma#6180]
### What happened?

We are facing issues with external service to allow mesh application to a non mesh Kafka endpoint communication.

Though it's working fine with the outbound port annotation - `traffic.kuma.io/exclude-outbound-ports` but not with the external service implementation.

We have tried with different kafka applications as well.

kuma version- **v2.0.0**

We have tested the below scenarios and attaching the respective logs.

- TLS  enabled (protocol - kafka)
- TLS  disabled (protocol - kafka)

 **NOTE : 2 different Kafka application is being used (TLS enabled & disabled)**

**1. External Service Code for TLS disabled**

```
apiVersion: kuma.io/v1alpha1
kind: ExternalService
mesh: default
metadata: 
  name: shared-emp-kafka-bootstrap
spec: 
  tags: 
    kuma.io/protocol: kafka
    kuma.io/service: shared-emp-kafka-bootstrap
  networking: 
    address: <KAFKA_DNS>:443
    tls: 
      enabled: false
```

**Error**

```
2023-01-31 12:13:15 DEBUG ClientUtils:113 - Resolved host 20.103.56.39 as 20.103.56.39
2023-01-31 12:13:15 DEBUG NetworkClient:991 - [Producer clientId=producer-1] Initiating connection to node 20.103.56.39:9094 (id: 0 rack: null) using address /20.103.56.39
2023-01-31 12:13:15 DEBUG Selector:531 - [Producer clientId=producer-1] Created socket with SO_RCVBUF = 32768, SO_SNDBUF = 131072, SO_TIMEOUT = 0 to node 0
2023-01-31 12:13:15 DEBUG NetworkClient:953 - [Producer clientId=producer-1] Completed connection to node 0. Fetching API versions.
2023-01-31 12:13:15 DEBUG NetworkClient:967 - [Producer clientId=producer-1] Initiating API versions fetch from node 0.
2023-01-31 12:13:15 DEBUG NetworkClient:521 - [Producer clientId=producer-1] Sending API_VERSIONS request with header RequestHeader(apiKey=API_VERSIONS, apiVersion=3, clientId=producer-1, correlationId=15) and timeout 30000 to node 0: ApiVersionsRequestData(clientSoftwareName='apache-kafka-java', clientSoftwareVersion='3.3.1')
2023-01-31 12:13:15 DEBUG Selector:606 - [Producer clientId=producer-1] Connection with /20.103.56.39 (channelId=0) disconnected
java.io.EOFException: null    at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:97) ~[java-kafka-producer-1.0-SNAPSHOT.jar:?]    at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452) ~[java-kafka-producer-1.0-SNAPSHOT.jar:?]    at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402) ~[java-kafka-producer-1.0-SNAPSHOT.jar:?]    at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674) ~[java-kafka-producer-1.0-SNAPSHOT.jar:?]    at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576) [java-kafka-producer-1.0-SNAPSHOT.jar:?]    at org.apache.kafka.common.network.Selector.poll(Selector.java:481) [java-kafka-producer-1.0-SNAPSHOT.jar:?]    at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:560) [java-kafka-producer-1.0-SNAPSHOT.jar:?]    at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:328) [java-kafka-producer-1.0-SNAPSHOT.jar:?]    at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:243) [java-kafka-producer-1.0-SNAPSHOT.jar:?]    at java.lang.Thread.run(Thread.java:833) [?:?]2023-01-31 12:13:15 INFO  NetworkClient:937 - [Producer clientId=producer-1] Node 0 disconnected.
2023-01-31 12:13:15 DEBUG NetworkClient:335 - [Producer clientId=producer-1] Cancelled in-flight API_VERSIONS request with correlation id 15 due to node 0 being disconnected (elapsed time since creation: 2ms, elapsed time since send: 2ms, request timeout: 30000ms): ApiVersionsRequestData(clientSoftwareName='apache-kafka-java', clientSoftwareVersion='3.3.1')
```

**2. External Service Code for TLS Enabled**

```
apiVersion: kuma.io/v1alpha1
kind: ExternalService
mesh: default
metadata: 
  name: shared-emp-kafka-bootstrap
spec: 
  tags: 
    kuma.io/protocol: kafka
    kuma.io/service: shared-emp-kafka-bootstrap
  networking: 
    address: <KAFKA_DNS>:443
    tls: 
      enabled: true
      caCert: 
        inline: <ENCYPTED DATA>
```

**Error**

```
[2023-02-08T09:09:16.401+0000] GC(46) Pause Young (Allocation Failure)
[2023-02-08T09:09:16.401+0000] GC(46) DefNew: 4097K->62K(4480K)
[2023-02-08T09:09:16.401+0000] GC(46) Tenured: 8361K->8362K(9816K)
[2023-02-08T09:09:16.401+0000] GC(46) Metaspace: 20047K->20047K(1067008K)
[2023-02-08T09:09:16.401+0000] GC(46) Pause Young (Allocation Failure) 12M->8M(13M) 0.557ms
[2023-02-08T09:09:16.401+0000] GC(46) User=0.01s Sys=0.00s Real=0.00s
73158 [kafka-producer-network-thread | producer-1] WARN org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Connection to node -1 (cdt-west-1-shared-emp-kafka-bootstrap.demo.net/240.0.0.27:443) terminated during authentication. This may happen due to any of the following reasons: (1) Authentication failed due to invalid credentials with brokers older than 1.0.0, (2) Firewall blocking Kafka TLS traffic (eg it may only allow HTTPS traffic), (3) Transient network issue.
73158 [kafka-producer-network-thread | producer-1] WARN org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Bootstrap broker cdt-west-1-shared-emp-kafka-bootstrap.demo.net:443 (id: -1 rack: null) disconnected
73463 [kafka-producer-network-thread | producer-1] WARN org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Connection to node -1 (cdt-west-1-shared-emp-kafka-bootstrap.demo.net/240.0.0.27:443) terminated during authentication. This may happen due to any of the following reasons: (1) Authentication failed due to invalid credentials with brokers older than 1.0.0, (2) Firewall blocking Kafka TLS traffic (eg it may only allow HTTPS traffic), (3) Transient network issue.
73463 [kafka-producer-network-thread | producer-1] WARN org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Bootstrap broker cdt-west-1-shared-emp-kafka-bootstrap.demo.net:443 (id: -1 rack: null) disconnected
```

**Comment by jakubdyszkiewicz** [comment]
> Triage: This won't work because kafka client first sends discovery request and then connects to brokers directly based on the response. You could try creating ExternalService for every broker.
>
> Alternatively, this filter may work https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/network_filters/kafka_mesh_filter but we don't expose it via native Kuma policy. We most likely don't build this into Envoy that we package with Kuma.

**Comment by jakubdyszkiewicz** [comment]
> Triage: feel free to reopen if this is still an issue
