### ISSUE TITLE
concurrent map read and map write in k8s controllers

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma#8160]
### What happened?

```
2023-10-26T17:06:41.730Z	INFO	controllers.Service	annotating service which is part of the mesh	{"service": {"name":"infra-backend-v2","namespace":"gateway-conformance-infra"}, "annotation": "ingress.kubernetes.io/service-upstream=true"}
fatal error: concurrent map read and map write

goroutine 2218 [running]:
github.com/kumahq/kuma/pkg/plugins/runtime/k8s/metadata.Annotations.getWithDefault(0x2e74b80?, {0x27cd7a0?, 0x5095920?}, 0x322a230, {0xc002495910?, 0x1, 0x418828?})
	github.com/kumahq/kuma/pkg/plugins/runtime/k8s/metadata/annotations.go:306 +0xb4
github.com/kumahq/kuma/pkg/plugins/runtime/k8s/metadata.Annotations.GetEnabledWithDefault(0x0?, 0x0, {0xc002495910?, 0xc0012acf20?, 0x265b7ac?})
	github.com/kumahq/kuma/pkg/plugins/runtime/k8s/metadata/annotations.go:198 +0x48
github.com/kumahq/kuma/pkg/plugins/runtime/k8s/metadata.Annotations.GetEnabled(0x19?, {0xc002495910?, 0xc0012acf20?, 0x0?})
	github.com/kumahq/kuma/pkg/plugins/runtime/k8s/metadata/annotations.go:194 +0x25
...

goroutine 2214 [runnable]:
github.com/kumahq/kuma/pkg/plugins/runtime/k8s/metadata.Annotations.GetEnabledWithDefault(0xc0012fff20?, 0x0, {0xc003401740?, 0x1?, 0x1?})
	github.com/kumahq/kuma/pkg/plugins/runtime/k8s/metadata/annotations.go:197 +0xa8
github.com/kumahq/kuma/pkg/plugins/runtime/k8s/metadata.Annotations.GetEnabled(...)
	github.com/kumahq/kuma/pkg/plugins/runtime/k8s/metadata/annotations.go:194
github.com/kumahq/kuma/pkg/plugins/runtime/k8s/controllers.(*PodConverter).dataplaneFor(0xc0009c2fb0, {0x3531968, 0xc002987140}, 0xc0029e8900, {0xc001434588, 0x1, 0x1}, {0x0, 0x0, 0x0})
	github.com/kumahq/kuma/pkg/plugins/runtime/k8s/controllers/pod_converter.go:85 +0xf1
github.com/kumahq/kuma/pkg/plugins/runtime/k8s/controllers.(*PodConverter).PodToDataplane(0x7fc503053b18?, {0x3531968, 0xc002987140}, 0xc001dd5680, 0xc001e39400?, 0x0?, {0xc001434588, 0x1, 0x1}, {0x0, ...})
	github.com/kumahq/kuma/pkg/plugins/runtime/k8s/controllers/pod_converter.go:44 +0xe7
```

Is the annotations map being shared between controllers somehow?

**Comment by lahabana** [comment]
I've had a look and it's very odd. controller-runtime is supposed to deep copy all objects meaning that sharing objects would not be possible.

AFAIK all our controllers are single threaded so this wouldn't happen within a reconciler.

The truncated trace here is a bit problematic too as we seem to have 2 stacks for different annotations (one is on the dp the other on the service).

I briefly suspected cachedResourceManager but that's highly unlikely as everything seems to be happening on pods and services not Kuma specific entities which would be in the resourceManager

**Comment by lukidzi** [comment]
Lately noticed on CI https://app.circleci.com/pipelines/gh/kumahq/kuma/36203/workflows/d2263cc2-c3c6-4f84-a7b9-7ee97d95efa0/jobs/591951/parallel-runs/0/steps/0-110
