### ISSUE TITLE
Fix `TestZoneSync` flaky-ness

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#9115]
### What happened?

I've seen at least 3 times `TestZoneSync` flake (timeout). This is the latest run https://github.com/kumahq/kuma/actions/runs/7742447857/job/21111613189 (try 1 failed, try 2 succeeded). Will try to find the other ones.

**Comment by lahabana** [comment]
Yes saw it too:

```
••••panic: test timed out after 10m0s
running tests:
	TestZoneSync (10m0s)

goroutine 251 [running]:
testing.(*M).startAlarm.func1()
	testing/testing.go:2259 +0x259
created by time.goFunc
	time/sleep.go:176 +0x45

goroutine 1 [chan receive, 10 minutes]:
testing.(*T).Run(0xc0006861a0, {0x40b3728, 0xc}, 0x41dd728)
	testing/testing.go:1649 +0x871
testing.runTests.func1(0x0?)
	testing/testing.go:2054 +0x85
testing.tRunner(0xc0006861a0, 0xc0005e3af8)
	testing/testing.go:1595 +0x262
testing.runTests(0xc0005099a0?, {0x62e09e0, 0x1, 0x1}, {0x1c?, 0x1e?, 0x6359880?})
	testing/testing.go:2052 +0x8ae
testing.(*M).Run(0xc0005099a0)
	testing/testing.go:1925 +0xcd8
main.main()
	_testmain.go:49 +0x2be

goroutine 16 [select, 10 minutes]:
github.com/onsi/ginkgo/v2/internal.RegisterForProgressSignal.func1()
	github.com/onsi/ginkgo/v2@v2.15.0/internal/progress_report.go:32 +0xc7
created by github.com/onsi/ginkgo/v2/internal.RegisterForProgressSignal in goroutine 63
	github.com/onsi/ginkgo/v2@v2.15.0/internal/progress_report.go:30 +0x189

goroutine 43 [select, 10 minutes]:
github.com/onsi/ginkgo/v2/internal/interrupt_handler.(*InterruptHandler).registerForInterrupts.func2(0x0)
	github.com/onsi/ginkgo/v2@v2.15.0/internal/interrupt_handler/interrupt_handler.go:131 +0x125
created by github.com/onsi/ginkgo/v2/internal/interrupt_handler.(*InterruptHandler).registerForInterrupts in goroutine 63
	github.com/onsi/ginkgo/v2@v2.15.0/internal/interrupt_handler/interrupt_handler.go:128 +0x2bd

goroutine 63 [select, 9 minutes]:
github.com/onsi/ginkgo/v2/internal.(*Suite).runNode(_, {0x3, 0x20, {0x0, 0x0}, 0xc000724d60, {{0x507a520, 0x3a}, 0x72, {0x0, ...}, ...}, ...}, ...)
	github.com/onsi/ginkgo/v2@v2.15.0/internal/suite.go:911 +0x1a0f
github.com/onsi/ginkgo/v2/internal.(*group).attemptSpec(0xc00097ead8, 0x1, {{0xc000b5e900?, 0xc0008db980?, 0x1?}, 0x0?})
	github.com/onsi/ginkgo/v2@v2.15.0/internal/group.go:286 +0x2b45
github.com/onsi/ginkgo/v2/internal.(*group).run(0xc00097ead8, {0xc0001d5f60, 0x1, 0x1})
	github.com/onsi/ginkgo/v2@v2.15.0/internal/group.go:349 +0x1228
github.com/onsi/ginkgo/v2/internal.(*Suite).runSpecs(0xc0007f5500, {0x40c7565, 0x15}, {0x638f040, 0x0, 0x0}, {0xc00007a504, 0x2d}, 0x0, {0xc000b60100, ...})
	github.com/onsi/ginkgo/v2@v2.15.0/internal/suite.go:489 +0x1292
github.com/onsi/ginkgo/v2/internal.(*Suite).Run(_, {_, _}, {_, _, _}, {_, _}, _, {0x45fbc90, ...}, ...)
	github.com/onsi/ginkgo/v2@v2.15.0/internal/suite.go:130 +0x5f8
github.com/onsi/ginkgo/v2.RunSpecs({0x45a9de0, 0xc000686340}, {0x40c7565, 0x15}, {0x0, 0x0, 0x0})
	github.com/onsi/ginkgo/v2@v2.15.0/core_dsl.go:300 +0xeab
github.com/kumahq/kuma/pkg/test.runSpecs(0xc00081de00?, {0x40c7565, 0x15})
	github.com/kumahq/kuma/pkg/test/ginkgo.go:56 +0x19f
github.com/kumahq/kuma/pkg/test.RunSpecs(0x0?, {0x40c7565, 0x15})
	github.com/kumahq/kuma/pkg/test/ginkgo.go:28 +0x165
github.com/kumahq/kuma/pkg/kds/v2/client_test.TestZoneSync(0x0?)
	github.com/kumahq/kuma/pkg/kds/v2/client/remote_suite_test.go:10 +0x33
testing.tRunner(0xc000686340, 0x41dd728)
	testing/testing.go:1595 +0x262
created by testing.(*T).Run in goroutine 1
	testing/testing.go:1648 +0x846

goroutine 42 [syscall, 10 minutes]:
os/signal.signal_recv()
	runtime/sigqueue.go:152 +0x29
os/signal.loop()
	os/signal/signal_unix.go:23 +0x1d
created by os/signal.Notify.func1.1 in goroutine 63
	os/signal/signal.go:151 +0x47

goroutine 258 [semacquire, 9 minutes]:
sync.runtime_Semacquire(0xc00086bf28?)
	runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0xc00086bf20)
	sync/waitgroup.go:116 +0xa5
github.com/kumahq/kuma/pkg/kds/v2/client_test.glob..func1.3.3()
	github.com/kumahq/kuma/pkg/kds/v2/client/zone_sync_test.go:110 +0xef
github.com/kumahq/kuma/pkg/kds/v2/client_test.glob..func1.4()
	github.com/kumahq/kuma/pkg/kds/v2/client/zone_sync_test.go:115 +0x3c
github.com/onsi/ginkgo/v2/internal.extractBodyFunction.func3({0xc0014c6790, 0xc000aabfa0})
	github.com/onsi/ginkgo/v2@v2.15.0/internal/node.go:463 +0x2f
github.com/onsi/ginkgo/v2/internal.(*Suite).runNode.func3()
	github.com/onsi/ginkgo/v2@v2.15.0/internal/suite.go:889 +0x14c
created by github.com/onsi/ginkgo/v2/internal.(*Suite).runNode in goroutine 63
	github.com/onsi/ginkgo/v2@v2.15.0/internal/suite.go:876 +0x1517

goroutine 246 [sync.RWMutex.RLock, 9 minutes]:
sync.runtime_SemacquireRWMutexR(0xc00096a538?, 0x6?, 0x4ade99?)
	runtime/sema.go:82 +0x25
sync.(*RWMutex).RLock(0xc00096a528)
	sync/rwmutex.go:71 +0x65
github.com/envoyproxy/go-control-plane/pkg/cache/v3.(*snapshotCache).CreateDeltaWatch.(*snapshotCache).cancelDeltaWatch.func1()
	github.com/envoyproxy/go-control-plane@v0.12.0/pkg/cache/v3/simple.go:614 +0x6f
github.com/envoyproxy/go-control-plane/pkg/server/delta/v3.(*watch).Cancel(...)
	github.com/envoyproxy/go-control-plane@v0.12.0/pkg/server/delta/v3/watches.go:50
github.com/envoyproxy/go-control-plane/pkg/server/delta/v3.(*server).processDelta(0xc000afc800, {0x7f93500a4e78, 0xc0001664e0}, 0xc000b28e40, {0x0, 0x0})
	github.com/envoyproxy/go-control-plane@v0.12.0/pkg/server/delta/v3/server.go:215 +0x932
github.com/envoyproxy/go-control-plane/pkg/server/delta/v3.(*server).DeltaStreamHandler(0x0?, {0x7f93500a4e78?, 0xc0001664e0}, {0x0, 0x0})
	github.com/envoyproxy/go-control-plane@v0.12.0/pkg/server/delta/v3/server.go:250 +0x12f
github.com/kumahq/kuma/pkg/kds/v2/server.(*server).GlobalToZoneSync(0xc000bbf6f8, {0x45fbab8?, 0xc000afc900})
	github.com/kumahq/kuma/pkg/kds/v2/server/kds.go:35 +0x11c
github.com/kumahq/kuma/pkg/kds/v2/client_test.glob..func1.3.1()
	github.com/kumahq/kuma/pkg/kds/v2/client/zone_sync_test.go:89 +0xd7
created by github.com/kumahq/kuma/pkg/kds/v2/client_test.glob..func1.3 in goroutine 227
	github.com/kumahq/kuma/pkg/kds/v2/client/zone_sync_test.go:84 +0x78b

goroutine 182 [select, 9 minutes]:
github.com/envoyproxy/go-control-plane/pkg/cache/v3.(*snapshotCache).respondDelta(0xc00096a4e0, {0x45f2f88, 0x638f040}, {0x45f4778, 0xc000a71e20}, 0xc0001f[448](https://github.com/kumahq/kuma/actions/runs/7784302807/job/21224579520?pr=9094#step:6:449)0, 0xc00096b020, {0x1, 0xc0001284b0, 0xc000128510, ...})
	github.com/envoyproxy/go-control-plane@v0.12.0/pkg/cache/v3/simple.go:597 +0x75e
github.com/envoyproxy/go-control-plane/pkg/cache/v3.(*snapshotCache).respondDeltaWatches(0xc00096a4e0, {0x45f2f88, 0x638f040}, 0xc0006ed8c0, {0x45f[477](https://github.com/kumahq/kuma/actions/runs/7784302807/job/21224579520?pr=9094#step:6:478)8?, 0xc000a71e20?})
	github.com/envoyproxy/go-control-plane@v0.12.0/pkg/cache/v3/simple.go:326 +0x2df
github.com/envoyproxy/go-control-plane/pkg/cache/v3.(*snapshotCache).SetSnapshot(0xc00096a4e0, {0x45f2f88, 0x638f040}, {0xc000333dc9, 0x7}, {0x45f4778?, 0xc000a71e20?})
	github.com/envoyproxy/go-control-plane@v0.12.0/pkg/cache/v3/simple.go:242 +0x31e
github.com/kumahq/kuma/pkg/kds/v2/reconcile.(*reconciler).Reconcile(0xc000371570, {0x45f2f88, 0x638f040}, 0xc000b72410, 0x7?, {{0x45f92c8?, 0xc000be5410?}, 0x0?})
	github.com/kumahq/kuma/pkg/kds/v2/reconcile/reconciler.go:96 +0x339
github.com/kumahq/kuma/pkg/kds/v2/server.newSyncTracker.func1.4({0xc000100000, 0xc000ab1ed4})
	github.com/kumahq/kuma/pkg/kds/v2/server/components.go:133 +0x162
github.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).onTick(0xc0005f8540, {0x45f3068, 0xc00071d1d0})
	github.com/kumahq/kuma/pkg/util/watchdog/watchdog.go:70 +0xc6
github.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).Start(0xc0005f8[540](https://github.com/kumahq/kuma/actions/runs/7784302807/job/21224579520?pr=9094#step:6:541), 0xc0006261e0)
	github.com/kumahq/kuma/pkg/util/watchdog/watchdog.go:40 +0x2e5
created by github.com/kumahq/kuma/pkg/util/xds/v3.(*watchdogCallbacks).OnStreamDeltaRequest in goroutine 246
	github.com/kumahq/kuma/pkg/util/xds/v3/watchdog_callbacks.go:173 +0x3d8

goroutine 183 [select]:
github.com/kumahq/kuma/pkg/kds/status.(*zoneInsightSink).Start(0xc0008b2840, {0x45f2f88, 0x638f040}, 0xc000b28ea0)
	github.com/kumahq/kuma/pkg/kds/status/status_sink.go:125 +0x4a9
created by github.com/kumahq/kuma/pkg/kds/status.(*statusTracker).onStreamRequest in goroutine 246
	github.com/kumahq/kuma/pkg/kds/status/status_tracker.go:179 +0x73d

goroutine 184 [select, 9 minutes]:
github.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).Start.func1()
	github.com/kumahq/kuma/pkg/util/watchdog/watchdog.go:29 +0xbb
created by github.com/kumahq/kuma/pkg/util/watchdog.(*SimpleWatchdog).Start in goroutine 182
	github.com/kumahq/kuma/pkg/util/watchdog/watchdog.go:28 +0x225
```

**Comment by lobkovilya** [comment]
The flake should be fixed by [downgrading go-control-plane](https://github.com/kumahq/kuma/pull/9163) library. Closing this one in favor of https://github.com/kumahq/kuma/issues/9580
